services:
  - type: web
    name: bullet-hell
    runtime: java
    buildCommand: ./mvnw package -DskipTests
    startCommand: java -jar target/game-0.0.1-SNAPSHOT.jar
    envVars:
      - key: MONGODB_URI
        sync: false
